defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: a928f07b-2e93-414a-ac32-39a0f05ceacf # Homepage
handle: homepage
maxAuthors: 1
name: Homepage
previewTargets:
  -
    label: Homepage
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  31861c7c-e659-40f7-ad0e-98ecdba93de8: # Firestarter
    enabledByDefault: true
    hasUrls: true
    template: null
    uriFormat: __home__
type: single
