dateModified: 1769447659
email:
  fromEmail: developer@firebellydesign.com
  fromName: Firestarter
  transportType: craft\mail\transportadapters\Sendmail
meta:
  __names__:
    851c9ce6-5d2d-4557-8b85-d9456fbe5b60: Homepage # Homepage
    8062c823-6463-47c9-9282-6a418395d03f: Heading # Heading
    31861c7c-e659-40f7-ad0e-98ecdba93de8: Firestarter # Firestarter
    311403d1-3dae-4f9e-aaed-871f09bd6c25: Pages # Pages
    57911354-86d0-4e1a-bd4c-fc02d49d5e69: Page # Page
    93884659-5d48-4374-bcb2-a3ffd332fc83: Simple # Simple
    a928f07b-2e93-414a-ac32-39a0f05ceacf: Homepage # Homepage
    a64493a9-3558-4984-82a5-446587987ba0: Firestarter # Firestarter
    bd170d86-9f68-495a-8855-8ff0af7db2b0: 'Public Schema' # Public Schema
    d1b9705e-df80-4160-859a-e37f574d4ea4: 'Private Schema' # Private Schema
    d760b96a-0f1c-40a2-90be-76015cca0ef8: Body # Body
plugins:
  ckeditor:
    edition: standard
    enabled: true
    schemaVersion: 3.0.0.0
system:
  edition: solo
  live: true
  name: Firestarter
  schemaVersion: 5.8.0.3
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  require2fa: false
  requireEmailVerification: true
